### ISSUE TITLE
Mission patch deadline feature doesn't work

### ISSUE THREAD

**Issue by S-Garry** [quan0715/grouping_application#108]
前端使用網址為 "localhost:8000/api/activities/{id}/" 來更新 mission deadline
前端在上傳轉為 json 檔之前，確認為已更改的日期，但更新所回傳的資料仍為未更新前的資料
![image](https://github.com/quan0715/grouping_application/assets/97837305/ebe11093-180d-48b5-968b-32653419a217)

**Comment by Bryant-Tang** [comment]
provide your request body, plz.

**Comment by S-Garry** [comment]
{title: test title, description: test introduction, creator: 4, belong_workspace: 1, mission: {deadline:
2024-01-19T17:33:19.001Z, state: 21}, notifications: []}

**Comment by Bryant-Tang** [comment]
at line 7, should be
"deadline": "2024-01-19T17:33:19.001Z",

**Comment by S-Garry** [comment]
![image](https://github.com/quan0715/grouping_application/assets/97837305/be6175d9-3af0-4ef3-a9e7-c8986c434ec8)
