### ISSUE TITLE
Auto create workspace when create user

### ISSUE THREAD

**Issue by Bryant-Tang** [quan0715/grouping_application#59]
Create a workspace contains only the creator when a new user sign up.

**Comment by Bryant-Tang** [comment]
@quan0715 what's the value of theme_color, workspace_name, description, photo that set to the auto created wrokspace?

**Comment by quan0715** [comment]
workspace_name : ${user_name} 的個人工作區
description: ${user_name} 的個人工作區
photo: ${user_photo_data}
theme_color: 1
