### ISSUE TITLE
flutter 的 container 無法同時使用 BorderRadius 跟 Border (準確來說是 BorderSide)

### ISSUE THREAD

**Issue by S-Garry** [quan0715/grouping_application#82]
flutter document 有限制說，如果有設定 BorderRadius 就不能使用 BorderSide 因為可能會造成要描繪圓角但另一邊可能為空的問題等等

當前影響到的檔案 app_log_message_card, color_card_widget

- 發生錯誤的地方
1. 登入畫面中，在不輸入任何狀況下直接按登入
![image](https://github.com/quan0715/grouping_application/assets/97837305/a35fe16c-4a83-49b4-b742-7381564617b0)

2. 登入畫面中，輸入錯誤的帳密的狀況下按登入
![image](https://github.com/quan0715/grouping_application/assets/97837305/ade84c2d-ed5a-4f66-b4d1-03d47df828b9)

- 發生錯誤的檔案
`grouping_application/grouping_flutter/lib/app/presentation/components/data_display/app_log_message_card.dart:113:16`

- 錯誤訊息
```
════════════════╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═══════════════════ 

The following assertion was thrown during paint():
Assertion failed: file:///C:/flutter/packages/flutter/lib/src/painting/box_border.dart:661:16
borderRadius == null || borderRadius == BorderRadius.zero
"A hairline border like `BorderSide(width: 0.0, style: BorderStyle.solid)` can only be drawn when
BorderRadius is zero or null."
```

**Comment by quan0715** [comment]
但我發現這個好像是因為版本問題導致的原因
我的版本是 3.16.1 所以不會有問題
但我在 merge 你的PR進去後因為套件相依問題而降版到 3.13 就發生了這個問題，可能先把radius 註解掉或在外面在套一層 COntainer 即可，未來在想辦法處理。
